<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class OrderCreateRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, mixed>
     */
    public function rules()
    {
        return [
            'summ_from' => 'required|numeric',
            'summ_to' => 'required|numeric',
            'wallet_to' => 'required',
            'email' => 'required',
        ];
    }

    public function messages()
    {
        return [
            'summ_from.required' => __('Недопустимо'),
            'summ_from.numeric' => __('Недопустимо'),
            'summ_to.required' => __('Недопустимо'),
            'summ_to.numeric' => __('Недопустимо'),
            'wallet_to.required' => __('Неверный номер счета. Указан неправильный реквизит'),
            'email.required' => __('Поле E-mail является обязательным.'),
        ];
//        return parent::messages(); // TODO: Change the autogenerated stub
    }
}
